spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservice


server:
  port: 8091

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defultZone: http://localhost:8761/eureka

