server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pgmicroservice
    username: postgres
    password: root


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




