
server:
  port: 8093

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/akashkumarsky/HotelMicroservice-config
          clone-on-start: true
