
server:
  port: 8092

spring:
  application:
    name: API-GATWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: USERSERVICE
            uri: lb://USERSERVICE
            predicates:
              - path=/user/**

          - id: HOTELSERVICE
            uri: lb://HOTELSERVICE
            predicates:
              - path=/hotels/**

          - id: RATING
            uri: lb://RATING
            predicates:
              - path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defultZone: http://localhost:8761/eureka
